framework:
    translator:
        paths:
            - '%kernel.project_dir%/src/Container/AuthSection/ResetPassword/UI/WEB/Translation'
            - '%kernel.project_dir%/src/Container/AuthSection/ResetPassword/Translation'