security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        db:
            entity:
                class: App\Container\User\Entity\Doc\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        admin:
#            pattern: admin
#            lazy: true
#
#            form_login:
#                provider:
#                login_path: admin.auth.login
#                username_parameter: login
#                password_parameter: password
#                check_path: admin.auth.login
#                failure_path: admin.auth.login
#                enable_csrf: true
#                csrf_token_id: '%auth_csrf_token_id%'
#                csrf_parameter: '%form.type_extension.csrf.field_name%'
#                default_target_path: admin.auth.home
#                use_referer: true
#
#            logout:
#                path: auth.logout
#                target: '%app_default_route%'

        main:
            lazy: true

            custom_authenticators:
                - app.authentication.main
                - app.authentication.admin
            entry_point: App\Ship\AuthEntryPoint


#            form_login:
#                provider: db
#                login_path: auth.login
#                username_parameter: login
#                password_parameter: password
#                check_path: auth.login
#                failure_path: auth.login
#                enable_csrf: true
#                csrf_token_id: '%auth_csrf_token_id%'
#                csrf_parameter: '%form.type_extension.csrf.field_name%'
#                default_target_path: '%app_default_route%'
#                use_referer: false

            logout:
                path: auth.logout
                target: '%app_default_route%'

            remember_me:
                remember_me_parameter: remember_me
                signature_properties:
                    - password
                    - email
                    - isActive
                lifetime: 604800

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon

        firewalls:
            main:
                form_login:
                    enable_csrf: false