services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    App\Container\AdminSection\Category\:
        resource: '%kernel.project_dir%/src/Container/AdminSection/Category'