framework:
    translator:
        paths:
            - '%kernel.project_dir%/src/Container/AdminSection/Category/UI/WEB/Translation'
            - '%kernel.project_dir%/src/Container/AdminSection/Category/Translation'
