services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    App\Container\Auth\:
        resource: '%kernel.project_dir%/src/Container/Auth'