when@dev:
    framework:
        mailer:
            dsn: null://null
            envelope:
                sender: '%env(MAILER_SENDER)%'

when@prod:
    framework:
        mailer:
            dsn: '%env(MAILER_DSN)%'
            envelope:
                sender: '%env(MAILER_SENDER)%'
            headers:
                From: '%env(APP_NAME)% <%env(MAILER_SENDER)%>'
