framework:
    rate_limiter:
        send_email:
            policy: fixed_window
            limit: 1
            interval: 1 minutes

when@test:
    framework:
        rate_limiter:
            send_email:
                limit: 100