framework:
    default_locale: ru

    enabled_locales:
        - ru
        - en

    set_locale_from_accept_language: '%set_locale_from_accept_language%'

    translator:
        default_path: '%kernel.project_dir%/src/Ship/Translation'

        fallbacks:
            - ru