twig:
    default_path: '%kernel.project_dir%/src/Ship/View'

    form_theme:
        - 'bootstrap_5_layout.html.twig'

    paths:
        '%kernel.project_dir%/src/Ship/View': ship

    globals:
        csrf_parameter: '%csrf_parameter%'
        csrf_token_id: '%csrf_token_id%'
        app_name: '%app_name%'

    date:
        timezone: Europe/Moscow

when@test:
    twig:
        strict_variables: true