imports:
    - { resource: ../../../src/Container/Locale/Config/ }
    - { resource: ../../../src/Container/News/Config/ }
    - { resource: ../../../src/Container/Home/Config/ }
    - { resource: ../../../src/Container/AuthSection/Auth/Config/ }
    - { resource: ../../../src/Container/AuthSection/ResetPassword/Config/ }
    - { resource: ../../../src/Container/User/Config/ }
    - { resource: ../../../src/Container/Profile/Config/ }

    # admin section
    - { resource: ../../../src/Container/AdminSection/Home/Config/ }
    - { resource: ../../../src/Container/AdminSection/Category/Config/ }
    - { resource: ../../../src/Container/AdminSection/User/Config/ }
    - { resource: ../../../src/Container/AdminSection/Auth/Config/ }