imports:
    - { resource: ../../../src/Container/Locale/Config/ }
    - { resource: ../../../src/Container/News/Config/ }
    - { resource: ../../../src/Container/Home/Config/ }
    - { resource: ../../../src/Container/Auth/Config/ }
    - { resource: ../../../src/Container/User/Config/ }
    - { resource: ../../../src/Container/Profile/Config/ }