services:
    RuntimeException:
        synthetic: true
        tags: [{ name: app.exception, code: 500, loggable: true }]

    Symfony\Component\HttpKernel\Exception\HttpException:
        tags: [{ name: app.exception, code: 404, hidden: false }]