services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    App\Container\AuthSection\ResetPassword\:
        resource: '%kernel.project_dir%/src/Container/AuthSection/ResetPassword'