parameters:
    auth_csrf_token_id: authenticate
    auth_default_path: home.main

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    App\Container\AuthSection\Auth\:
        resource: '%kernel.project_dir%/src/Container/AuthSection/Auth'

    App\Container\AuthSection\Auth\Listener\SendVerificationEmailListener:
        tags:
            - { name: kernel.event_listener, event: user.registered }