parameters:
    app_name: '%env(APP_NAME)%'
    app_default_route: home.main
    app_public_dir: '%kernel.project_dir%/public'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Ship\:
        resource: '%kernel.project_dir%/src/Ship'
        exclude: '%kernel.project_dir%/src/Ship/Parent'

    App\Ship\Listener\RequestContextListener:
        arguments:
            $host: '%env(APP_HOST)%'
            $httpPort: '%env(int:APP_HTTP_PORT)%'
            $httpsPort: '%env(int:APP_HTTPS_PORT)%'
            $scheme: '%env(APP_SCHEME)%'

    App\Ship\Listener\ExceptionListener:
        arguments:
            $debug: '%kernel.debug%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: -1 }

    App\Ship\Listener\OnlyGuestListener:
        arguments:
            $fallbackRoute: '%app_default_route%'

    App\Ship\Service\Doctrine\PurgerFactory:
        tags:
            - { name: doctrine.fixtures.purger_factory, alias: purger }

    App\Ship\Validator\ControllerValidator:
        arguments:
            $storageErrorAdapter: '@App\Ship\Validator\SessionFlashBagStorageErrorAdapter'

    app.success_handler.main:
        class: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler
        arguments:
            $options:
                use_referer: true
                login_path: auth.login
                default_target_path: home.main

    app.success_handler.admin:
        class: Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler
        arguments:
            $options:
                use_referer: true
                login_path: admin.auth.login
                default_target_path: admin.home.main


    app.authentication.main:
        class: App\Ship\CustomAuthenticator
        arguments:
            $userLoader: '@App\Ship\MainUserLoader'
            $successHandler: '@app.success_handler.main'
            $options:
                username_parameter: login
                password_parameter: password
                check_path: auth.login
                csrf_parameter: '%form.type_extension.csrf.field_name%'
                csrf_token_id: '%auth_csrf_token_id%'

    app.authentication.admin:
        class: App\Ship\CustomAuthenticator
        arguments:
            $userLoader: '@App\Ship\AdminUserLoader'
            $successHandler: '@app.success_handler.admin'
            $options:
                username_parameter: login
                password_parameter: password
                check_path: admin.auth.login
                csrf_parameter: '%form.type_extension.csrf.field_name%'
                csrf_token_id: '%auth_csrf_token_id%'