parameters:
    app_name: '%env(APP_NAME)%'
    app_default_route: home.main

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Ship\:
        resource: '%kernel.project_dir%/src/Ship'
        exclude: '%kernel.project_dir%/src/Ship/Parent'

    App\Ship\Listener\RequestContextListener:
        arguments:
            $host: '%env(APP_HOST)%'
            $httpPort: '%env(int:APP_HTTP_PORT)%'
            $httpsPort: '%env(int:APP_HTTPS_PORT)%'
            $scheme: '%env(APP_SCHEME)%'

    App\Ship\Listener\ExceptionListener:
        arguments:
            $debug: '%kernel.debug%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: -1 }

    App\Ship\Listener\OnlyGuestListener:
        arguments:
            $fallbackRoute: '%app_default_route%'

    App\Ship\Service\Doctrine\PurgerFactory:
        tags:
            - { name: doctrine.fixtures.purger_factory, alias: purger }

    App\Ship\Validator\ControllerValidator:
        arguments:
            $storageErrorAdapter: '@App\Ship\Validator\SessionFlashBagStorageErrorAdapter'