services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true

    App\Container\AdminSection\User\:
        resource: '%kernel.project_dir%/src/Container/AdminSection/User'
        exclude: '%kernel.project_dir%/src/Container/AdminSection/User/Exception'